#!/bin/sh

pisys=`dirname "$0"`
pisys=`realpath "$pisys"`

docker run \
    "--env=http_proxy=$APT_PROXY" \
    "--env=PISYS_OWNER=$(id -u):$(id -g)" \
    -v "$pisys:/host" \
    pisys-bootstrap:latest \
        /host/target-build-prebase prebase.tar.xz
