#!/bin/sh

pisys=`dirname "$0"`
pisys=`realpath "$pisys"`

docker run \
    "--env=http_proxy=$APT_PROXY" \
    "--env=PISYS_OWNER=$(id -u):$(id -g)" \
    -v "$pisys:/host" \
    -v "$pisys/stage1:/target" \
    pisys-bootstrap:latest \
    /host/make-stage1
