#!/bin/sh
tarball=$1

if [ ! -f "/target/debootstrap/debootstrap" ]; then
   debootstrap \
       --arch armhf \
       --foreign \
       --components=main \
       --keyring /host/raspberrypi.gpg \
       stretch \
       /target \
       http://raspbian.raspberrypi.org/raspbian
fi
if [ ! -f /target/usr/bin/qemu-arm-static ]; then
    cp $(which qemu-arm-static) /target/usr/bin/
fi

tar -c \
    -J \
    --anchored \
    --exclude="./dev/*" \
    --exclude="./proc/*" \
    --exclude="./run/*" \
    --exclude="./sys/*" \
    -C /target \
    -f "/host/$tarball" \
    .
if [ -n "$PISYS_OWNER" ]; then
    chown "$PISYS_OWNER" "/host/$tarball"
fi
